#ifndef LCD_CONF_H_
#define LCD_CONF_H_

//#define LCD_PART_NUMBER K70DWN0V1F  //DEF_KENTEC
//#define LCD_PART_NUMBER K430WQAV4F
#define LCD_PART_NUMBER AT043TN24V7  //DEF_SKW
#endif /* LCD_CONF_H_ */
